# TABLES: TICKET DETAILS, FLIGHT TRIP, PASSENGERS
def make_booking():
    # INPUT: FLIGHT TRIP ID, LIST OF PASSENGER ID

    # CHECK HOW MANY SEATS THEY WILL NEED (BABY?)
    # CHECK THAT SEATS ARE AVAILABLE
    # IF SEATS ARE NOT AVAILABLE THEN RETURN: NOT AVAILABLE
    # OTHERWISE UPDATE NUMBER OF SEATS AVAILABLE

    # CHECK IF THEY'RE ELIGIBLE FOR DISCOUNT
    
    # FOR EACH PASSENGER
    # ADD FLIGHT TRIP ID/PASSENGER ID TO TICKET DETAILS TABLE
    # ADD COST OF TICKET TO TICKET DETAILS
    
    # RETURN: TICKET ID, COST OF TICKET (ANY DISCOUNT APPLIED), EXTRA FLIGHT DETAILS
