# TABLES: PASSENGER
def create_passenger():
    # INPUT: FIRST NAME, LAST NAME, DOB, PASSPORT NUMBER

    # SQL QUERY TO INPUT INTO PASSENGERS TABLE

    # OUTPUT: SUCCESSFUL MESSAGE


# TABLES: STAFF
def create_staff():
    # INPUT: FIRST NAME, LAST NAME, USERNAME, PASSWORD, PASSPORT NUMBER
    
    # SQL QUERY TO INPUT INTO STAFF TABLE

    # OUTPUT: SUCCESSFUL MESSAGE