# TABLES: FLIGHT TRIP, AIRPORTS
def create_flight_trip():
    # INPUT: DEPARTURE TIME, DEPARTURE AIRPORT, ARRIVAL AIRPORT, TICKET PRICE, TICKET DISCOUNT

    # ESTIMATE ARRIVAL TIME (1 hour for now)
    
    # RETURN: FLIGHT TRIP ID


# TABLES: FLIGHT TRIP, AIRCRAFT
def assign_aircraft(FlightTrip_id):
    # INPUT: FLIGHT TRIP ID

    # CHECK THAT IT's A VALID FLIGHT TRIP ID
    # FIND PLANE THAT IS AVAILABLE AND IN CORRECT LOCATION

    # RETURN: AIRCRAFT ID


# TABLES: FLIGHT TRIP, AIRCRAFT
def change_aircraft():
    # INPUT: FLIGHT TRIP ID

    # REMOVE PLANE ID AND UPDATE PLANE DETAILS TO NO LONGER HAVE DEPARTURE/ARRIVAL INFORMATION

    # CALL ASSIGN_AIRCRAFT() AGAIN
    # NEW PLANE ID = assign_aircraft()

    # RETURN: NEW AIRCRAFT ID
