# TABLES: FLIGHT STAFF, FLIGHT TRIP, STAFF
def assign_staff_to_flight():
    # INPUT: FLIGHT TRIP ID

    # FIND HOW MANY STAFF REQUIRED
    # CHECK WHO IS AVAILABLE

    # ASSIGN STAFF
    # UPDATE FLIGHT STAFF TABLE

    # RETURN: LIST OF STAFF ASSIGNED


# TABLES: FLIGHT TRIP, BOOKING DETAILS, FLIGHT STAFF, PASSENGERS, STAFF
def flight_attendees():
    # INPUT: FLIGHT TRIP ID

    # FIND ALL PASSENGERS/STAFF ON FLIGHT

    # RETURN: FLIGHT ATTENDEES LIST

